# Generated by Django 5.1 on 2025-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseschedule",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "critical"),
                    ("very_important", "very_important"),
                    ("important", "important"),
                    ("normal", "normal"),
                    ("not_important", "not_important"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
